// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Series series
// swagger:model Series
type Series struct {

	// A resource list containing characters which appear in comics in this series.
	Characters *CharacterList `json:"characters,omitempty"`

	// A resource list containing comics in this series.
	Comics *ComicList `json:"comics,omitempty"`

	// A resource list of creators whose work appears in comics in this series.
	Creators *CreatorList `json:"creators,omitempty"`

	// A description of the series.
	Description string `json:"description,omitempty"`

	// The last year of publication for the series (conventionally, 2099 for ongoing series) .
	EndYear int32 `json:"endYear,omitempty"`

	// A resource list containing events which take place in comics in this series.
	Events *EventList `json:"events,omitempty"`

	// The unique ID of the series resource.
	ID int32 `json:"id,omitempty"`

	// The date the resource was most recently modified.
	Modified string `json:"modified,omitempty"`

	// A summary representation of the series which follows this series.
	Next *SeriesSummary `json:"next,omitempty"`

	// A summary representation of the series which preceded this series.
	Previous *SeriesSummary `json:"previous,omitempty"`

	// The age-appropriateness rating for the series.
	Rating string `json:"rating,omitempty"`

	// The canonical URL identifier for this resource.
	ResourceURI string `json:"resourceURI,omitempty"`

	// The first year of publication for the series.
	StartYear int32 `json:"startYear,omitempty"`

	// A resource list containing stories which occur in comics in this series.
	Stories *StoryList `json:"stories,omitempty"`

	// The representative image for this series.
	Thumbnail *Image `json:"thumbnail,omitempty"`

	// The canonical title of the series.
	Title string `json:"title,omitempty"`

	// A set of public web site URLs for the resource.
	Urls []*URL `json:"urls"`
}

// Validate validates this series
func (m *Series) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCharacters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateComics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreators(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStories(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThumbnail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUrls(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Series) validateCharacters(formats strfmt.Registry) error {

	if swag.IsZero(m.Characters) { // not required
		return nil
	}

	if m.Characters != nil {
		if err := m.Characters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("characters")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateComics(formats strfmt.Registry) error {

	if swag.IsZero(m.Comics) { // not required
		return nil
	}

	if m.Comics != nil {
		if err := m.Comics.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("comics")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateCreators(formats strfmt.Registry) error {

	if swag.IsZero(m.Creators) { // not required
		return nil
	}

	if m.Creators != nil {
		if err := m.Creators.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("creators")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateEvents(formats strfmt.Registry) error {

	if swag.IsZero(m.Events) { // not required
		return nil
	}

	if m.Events != nil {
		if err := m.Events.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("events")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateNext(formats strfmt.Registry) error {

	if swag.IsZero(m.Next) { // not required
		return nil
	}

	if m.Next != nil {
		if err := m.Next.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("next")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validatePrevious(formats strfmt.Registry) error {

	if swag.IsZero(m.Previous) { // not required
		return nil
	}

	if m.Previous != nil {
		if err := m.Previous.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("previous")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateStories(formats strfmt.Registry) error {

	if swag.IsZero(m.Stories) { // not required
		return nil
	}

	if m.Stories != nil {
		if err := m.Stories.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stories")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateThumbnail(formats strfmt.Registry) error {

	if swag.IsZero(m.Thumbnail) { // not required
		return nil
	}

	if m.Thumbnail != nil {
		if err := m.Thumbnail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

func (m *Series) validateUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.Urls) { // not required
		return nil
	}

	for i := 0; i < len(m.Urls); i++ {
		if swag.IsZero(m.Urls[i]) { // not required
			continue
		}

		if m.Urls[i] != nil {
			if err := m.Urls[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("urls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Series) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Series) UnmarshalBinary(b []byte) error {
	var res Series
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
