// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SeriesSummary series summary
// swagger:model SeriesSummary
type SeriesSummary struct {

	// The canonical name of the series.
	Name string `json:"name,omitempty"`

	// The path to the individual series resource.
	ResourceURI string `json:"resourceURI,omitempty"`
}

// Validate validates this series summary
func (m *SeriesSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SeriesSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeriesSummary) UnmarshalBinary(b []byte) error {
	var res SeriesSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
