// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TextObject text object
// swagger:model TextObject
type TextObject struct {

	// The IETF language tag denoting the language the text object is written in.
	Language string `json:"language,omitempty"`

	// The text.
	Text string `json:"text,omitempty"`

	// The canonical type of the text object (e.g. solicit text, preview text, etc.).
	Type string `json:"type,omitempty"`
}

// Validate validates this text object
func (m *TextObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TextObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TextObject) UnmarshalBinary(b []byte) error {
	var res TextObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
