// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventIndividualParams creates a new GetEventIndividualParams object
// with the default values initialized.
func NewGetEventIndividualParams() *GetEventIndividualParams {
	var ()
	return &GetEventIndividualParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventIndividualParamsWithTimeout creates a new GetEventIndividualParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventIndividualParamsWithTimeout(timeout time.Duration) *GetEventIndividualParams {
	var ()
	return &GetEventIndividualParams{

		timeout: timeout,
	}
}

// NewGetEventIndividualParamsWithContext creates a new GetEventIndividualParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEventIndividualParamsWithContext(ctx context.Context) *GetEventIndividualParams {
	var ()
	return &GetEventIndividualParams{

		Context: ctx,
	}
}

// NewGetEventIndividualParamsWithHTTPClient creates a new GetEventIndividualParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEventIndividualParamsWithHTTPClient(client *http.Client) *GetEventIndividualParams {
	var ()
	return &GetEventIndividualParams{
		HTTPClient: client,
	}
}

/*GetEventIndividualParams contains all the parameters to send to the API endpoint
for the get event individual operation typically these are written to a http.Request
*/
type GetEventIndividualParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*EventID
	  A single event.

	*/
	EventID int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get event individual params
func (o *GetEventIndividualParams) WithTimeout(timeout time.Duration) *GetEventIndividualParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event individual params
func (o *GetEventIndividualParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event individual params
func (o *GetEventIndividualParams) WithContext(ctx context.Context) *GetEventIndividualParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event individual params
func (o *GetEventIndividualParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event individual params
func (o *GetEventIndividualParams) WithHTTPClient(client *http.Client) *GetEventIndividualParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event individual params
func (o *GetEventIndividualParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get event individual params
func (o *GetEventIndividualParams) WithApikey(apikey string) *GetEventIndividualParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get event individual params
func (o *GetEventIndividualParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithEventID adds the eventID to the get event individual params
func (o *GetEventIndividualParams) WithEventID(eventID int32) *GetEventIndividualParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get event individual params
func (o *GetEventIndividualParams) SetEventID(eventID int32) {
	o.EventID = eventID
}

// WithHash adds the hash to the get event individual params
func (o *GetEventIndividualParams) WithHash(hash string) *GetEventIndividualParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get event individual params
func (o *GetEventIndividualParams) SetHash(hash string) {
	o.Hash = hash
}

// WithTs adds the ts to the get event individual params
func (o *GetEventIndividualParams) WithTs(ts string) *GetEventIndividualParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get event individual params
func (o *GetEventIndividualParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventIndividualParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	// path param eventId
	if err := r.SetPathParam("eventId", swag.FormatInt32(o.EventID)); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
