// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/marvel-comics-api-data-loader/marvel/models"
)

// GetCreatorIndividualReader is a Reader for the GetCreatorIndividual structure.
type GetCreatorIndividualReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCreatorIndividualReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCreatorIndividualOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCreatorIndividualOK creates a GetCreatorIndividualOK with default headers values
func NewGetCreatorIndividualOK() *GetCreatorIndividualOK {
	return &GetCreatorIndividualOK{}
}

/*GetCreatorIndividualOK handles this case with default header values.

No response was specified
*/
type GetCreatorIndividualOK struct {
	Payload *models.CreatorDataWrapper
}

func (o *GetCreatorIndividualOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/creators/{creatorId}][%d] getCreatorIndividualOK  %+v", 200, o.Payload)
}

func (o *GetCreatorIndividualOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatorDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
