// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetComicCharacterCollectionParams creates a new GetComicCharacterCollectionParams object
// with the default values initialized.
func NewGetComicCharacterCollectionParams() *GetComicCharacterCollectionParams {
	var ()
	return &GetComicCharacterCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetComicCharacterCollectionParamsWithTimeout creates a new GetComicCharacterCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetComicCharacterCollectionParamsWithTimeout(timeout time.Duration) *GetComicCharacterCollectionParams {
	var ()
	return &GetComicCharacterCollectionParams{

		timeout: timeout,
	}
}

// NewGetComicCharacterCollectionParamsWithContext creates a new GetComicCharacterCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetComicCharacterCollectionParamsWithContext(ctx context.Context) *GetComicCharacterCollectionParams {
	var ()
	return &GetComicCharacterCollectionParams{

		Context: ctx,
	}
}

// NewGetComicCharacterCollectionParamsWithHTTPClient creates a new GetComicCharacterCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetComicCharacterCollectionParamsWithHTTPClient(client *http.Client) *GetComicCharacterCollectionParams {
	var ()
	return &GetComicCharacterCollectionParams{
		HTTPClient: client,
	}
}

/*GetComicCharacterCollectionParams contains all the parameters to send to the API endpoint
for the get comic character collection operation typically these are written to a http.Request
*/
type GetComicCharacterCollectionParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*ComicID
	  The comic id.

	*/
	ComicID int32
	/*Events
	  Return only characters which appear comics that took place in the specified events (accepts a comma-separated list of ids).

	*/
	Events []int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Limit
	  Limit the result set to the specified number of resources.

	*/
	Limit *int32
	/*ModifiedSince
	  Return only characters which have been modified since the specified date.

	*/
	ModifiedSince *strfmt.Date
	/*Name
	  Return only characters matching the specified full character name (e.g. Spider-Man).

	*/
	Name *string
	/*NameStartsWith
	  Return characters with names that begin with the specified string (e.g. Sp).

	*/
	NameStartsWith *string
	/*Offset
	  Skip the specified number of resources in the result set.

	*/
	Offset *int32
	/*OrderBy
	  Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed.

	*/
	OrderBy []string
	/*Series
	  Return only characters which appear the specified series (accepts a comma-separated list of ids).

	*/
	Series []int32
	/*Stories
	  Return only characters which appear the specified stories (accepts a comma-separated list of ids).

	*/
	Stories []int32
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithTimeout(timeout time.Duration) *GetComicCharacterCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithContext(ctx context.Context) *GetComicCharacterCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithHTTPClient(client *http.Client) *GetComicCharacterCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithApikey(apikey string) *GetComicCharacterCollectionParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithComicID adds the comicID to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithComicID(comicID int32) *GetComicCharacterCollectionParams {
	o.SetComicID(comicID)
	return o
}

// SetComicID adds the comicId to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetComicID(comicID int32) {
	o.ComicID = comicID
}

// WithEvents adds the events to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithEvents(events []int32) *GetComicCharacterCollectionParams {
	o.SetEvents(events)
	return o
}

// SetEvents adds the events to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetEvents(events []int32) {
	o.Events = events
}

// WithHash adds the hash to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithHash(hash string) *GetComicCharacterCollectionParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetHash(hash string) {
	o.Hash = hash
}

// WithLimit adds the limit to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithLimit(limit *int32) *GetComicCharacterCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithModifiedSince adds the modifiedSince to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithModifiedSince(modifiedSince *strfmt.Date) *GetComicCharacterCollectionParams {
	o.SetModifiedSince(modifiedSince)
	return o
}

// SetModifiedSince adds the modifiedSince to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetModifiedSince(modifiedSince *strfmt.Date) {
	o.ModifiedSince = modifiedSince
}

// WithName adds the name to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithName(name *string) *GetComicCharacterCollectionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetName(name *string) {
	o.Name = name
}

// WithNameStartsWith adds the nameStartsWith to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithNameStartsWith(nameStartsWith *string) *GetComicCharacterCollectionParams {
	o.SetNameStartsWith(nameStartsWith)
	return o
}

// SetNameStartsWith adds the nameStartsWith to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetNameStartsWith(nameStartsWith *string) {
	o.NameStartsWith = nameStartsWith
}

// WithOffset adds the offset to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithOffset(offset *int32) *GetComicCharacterCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithOrderBy(orderBy []string) *GetComicCharacterCollectionParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetOrderBy(orderBy []string) {
	o.OrderBy = orderBy
}

// WithSeries adds the series to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithSeries(series []int32) *GetComicCharacterCollectionParams {
	o.SetSeries(series)
	return o
}

// SetSeries adds the series to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetSeries(series []int32) {
	o.Series = series
}

// WithStories adds the stories to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithStories(stories []int32) *GetComicCharacterCollectionParams {
	o.SetStories(stories)
	return o
}

// SetStories adds the stories to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetStories(stories []int32) {
	o.Stories = stories
}

// WithTs adds the ts to the get comic character collection params
func (o *GetComicCharacterCollectionParams) WithTs(ts string) *GetComicCharacterCollectionParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get comic character collection params
func (o *GetComicCharacterCollectionParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetComicCharacterCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	// path param comicId
	if err := r.SetPathParam("comicId", swag.FormatInt32(o.ComicID)); err != nil {
		return err
	}

	var valuesEvents []string
	for _, v := range o.Events {
		valuesEvents = append(valuesEvents, swag.FormatInt32(v))
	}

	joinedEvents := swag.JoinByFormat(valuesEvents, "")
	// query array param events
	if err := r.SetQueryParam("events", joinedEvents...); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.ModifiedSince != nil {

		// query param modifiedSince
		var qrModifiedSince strfmt.Date
		if o.ModifiedSince != nil {
			qrModifiedSince = *o.ModifiedSince
		}
		qModifiedSince := qrModifiedSince.String()
		if qModifiedSince != "" {
			if err := r.SetQueryParam("modifiedSince", qModifiedSince); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.NameStartsWith != nil {

		// query param nameStartsWith
		var qrNameStartsWith string
		if o.NameStartsWith != nil {
			qrNameStartsWith = *o.NameStartsWith
		}
		qNameStartsWith := qrNameStartsWith
		if qNameStartsWith != "" {
			if err := r.SetQueryParam("nameStartsWith", qNameStartsWith); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesOrderBy := o.OrderBy

	joinedOrderBy := swag.JoinByFormat(valuesOrderBy, "")
	// query array param orderBy
	if err := r.SetQueryParam("orderBy", joinedOrderBy...); err != nil {
		return err
	}

	var valuesSeries []string
	for _, v := range o.Series {
		valuesSeries = append(valuesSeries, swag.FormatInt32(v))
	}

	joinedSeries := swag.JoinByFormat(valuesSeries, "")
	// query array param series
	if err := r.SetQueryParam("series", joinedSeries...); err != nil {
		return err
	}

	var valuesStories []string
	for _, v := range o.Stories {
		valuesStories = append(valuesStories, swag.FormatInt32(v))
	}

	joinedStories := swag.JoinByFormat(valuesStories, "")
	// query array param stories
	if err := r.SetQueryParam("stories", joinedStories...); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
