// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetComicsCollectionParams creates a new GetComicsCollectionParams object
// with the default values initialized.
func NewGetComicsCollectionParams() *GetComicsCollectionParams {
	var ()
	return &GetComicsCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetComicsCollectionParamsWithTimeout creates a new GetComicsCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetComicsCollectionParamsWithTimeout(timeout time.Duration) *GetComicsCollectionParams {
	var ()
	return &GetComicsCollectionParams{

		timeout: timeout,
	}
}

// NewGetComicsCollectionParamsWithContext creates a new GetComicsCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetComicsCollectionParamsWithContext(ctx context.Context) *GetComicsCollectionParams {
	var ()
	return &GetComicsCollectionParams{

		Context: ctx,
	}
}

// NewGetComicsCollectionParamsWithHTTPClient creates a new GetComicsCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetComicsCollectionParamsWithHTTPClient(client *http.Client) *GetComicsCollectionParams {
	var ()
	return &GetComicsCollectionParams{
		HTTPClient: client,
	}
}

/*GetComicsCollectionParams contains all the parameters to send to the API endpoint
for the get comics collection operation typically these are written to a http.Request
*/
type GetComicsCollectionParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*Characters
	  Return only comics which feature the specified characters (accepts a comma-separated list of ids).

	*/
	Characters []int32
	/*Collaborators
	  Return only comics in which the specified creators worked together (for example in which BOTH Stan Lee and Jack Kirby did work). Accepts a comma-separated list of ids.

	*/
	Collaborators []int32
	/*Creators
	  Return only comics which feature work by the specified creators (accepts a comma-separated list of ids).

	*/
	Creators []int32
	/*DateDescriptor
	  Return comics within a predefined date range.

	*/
	DateDescriptor *string
	/*DateRange
	  Return comics within a predefined date range.  Dates must be specified as date1,date2 (e.g. 2013-01-01,2013-01-02).  Dates are preferably formatted as YYYY-MM-DD but may be sent as any common date format.

	*/
	DateRange []int32
	/*DiamondCode
	  Filter by diamond code.

	*/
	DiamondCode *string
	/*DigitalID
	  Filter by digital comic id.

	*/
	DigitalID *int32
	/*Ean
	  Filter by EAN.

	*/
	Ean *string
	/*Events
	  Return only comics which take place in the specified events (accepts a comma-separated list of ids).

	*/
	Events []int32
	/*Format
	  Filter by the issue format (e.g. comic, digital comic, hardcover).

	*/
	Format *string
	/*FormatType
	  Filter by the issue format type (comic or collection).

	*/
	FormatType *string
	/*HasDigitalIssue
	  Include only results which are available digitally.

	*/
	HasDigitalIssue *bool
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Isbn
	  Filter by ISBN.

	*/
	Isbn *string
	/*Issn
	  Filter by ISSN.

	*/
	Issn *string
	/*IssueNumber
	  Return only issues in series whose issue number matches the input.

	*/
	IssueNumber *int32
	/*Limit
	  Limit the result set to the specified number of resources.

	*/
	Limit *int32
	/*ModifiedSince
	  Return only comics which have been modified since the specified date.

	*/
	ModifiedSince *strfmt.Date
	/*NoVariants
	  Exclude variants (alternate covers, secondary printings, director's cuts, etc.) from the result set.

	*/
	NoVariants *bool
	/*Offset
	  Skip the specified number of resources in the result set.

	*/
	Offset *int32
	/*OrderBy
	  Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed.

	*/
	OrderBy []string
	/*Series
	  Return only comics which are part of the specified series (accepts a comma-separated list of ids).

	*/
	Series []int32
	/*SharedAppearances
	  Return only comics in which the specified characters appear together (for example in which BOTH Spider-Man and Wolverine appear). Accepts a comma-separated list of ids.

	*/
	SharedAppearances []int32
	/*StartYear
	  Return only issues in series whose start year matches the input.

	*/
	StartYear *int32
	/*Stories
	  Return only comics which contain the specified stories (accepts a comma-separated list of ids).

	*/
	Stories []int32
	/*Title
	  Return only issues in series whose title matches the input.

	*/
	Title *string
	/*TitleStartsWith
	  Return only issues in series whose title starts with the input.

	*/
	TitleStartsWith *string
	/*Ts
	  [Auth] timestamp

	*/
	Ts string
	/*Upc
	  Filter by UPC.

	*/
	Upc *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get comics collection params
func (o *GetComicsCollectionParams) WithTimeout(timeout time.Duration) *GetComicsCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get comics collection params
func (o *GetComicsCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get comics collection params
func (o *GetComicsCollectionParams) WithContext(ctx context.Context) *GetComicsCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get comics collection params
func (o *GetComicsCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get comics collection params
func (o *GetComicsCollectionParams) WithHTTPClient(client *http.Client) *GetComicsCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get comics collection params
func (o *GetComicsCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get comics collection params
func (o *GetComicsCollectionParams) WithApikey(apikey string) *GetComicsCollectionParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get comics collection params
func (o *GetComicsCollectionParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithCharacters adds the characters to the get comics collection params
func (o *GetComicsCollectionParams) WithCharacters(characters []int32) *GetComicsCollectionParams {
	o.SetCharacters(characters)
	return o
}

// SetCharacters adds the characters to the get comics collection params
func (o *GetComicsCollectionParams) SetCharacters(characters []int32) {
	o.Characters = characters
}

// WithCollaborators adds the collaborators to the get comics collection params
func (o *GetComicsCollectionParams) WithCollaborators(collaborators []int32) *GetComicsCollectionParams {
	o.SetCollaborators(collaborators)
	return o
}

// SetCollaborators adds the collaborators to the get comics collection params
func (o *GetComicsCollectionParams) SetCollaborators(collaborators []int32) {
	o.Collaborators = collaborators
}

// WithCreators adds the creators to the get comics collection params
func (o *GetComicsCollectionParams) WithCreators(creators []int32) *GetComicsCollectionParams {
	o.SetCreators(creators)
	return o
}

// SetCreators adds the creators to the get comics collection params
func (o *GetComicsCollectionParams) SetCreators(creators []int32) {
	o.Creators = creators
}

// WithDateDescriptor adds the dateDescriptor to the get comics collection params
func (o *GetComicsCollectionParams) WithDateDescriptor(dateDescriptor *string) *GetComicsCollectionParams {
	o.SetDateDescriptor(dateDescriptor)
	return o
}

// SetDateDescriptor adds the dateDescriptor to the get comics collection params
func (o *GetComicsCollectionParams) SetDateDescriptor(dateDescriptor *string) {
	o.DateDescriptor = dateDescriptor
}

// WithDateRange adds the dateRange to the get comics collection params
func (o *GetComicsCollectionParams) WithDateRange(dateRange []int32) *GetComicsCollectionParams {
	o.SetDateRange(dateRange)
	return o
}

// SetDateRange adds the dateRange to the get comics collection params
func (o *GetComicsCollectionParams) SetDateRange(dateRange []int32) {
	o.DateRange = dateRange
}

// WithDiamondCode adds the diamondCode to the get comics collection params
func (o *GetComicsCollectionParams) WithDiamondCode(diamondCode *string) *GetComicsCollectionParams {
	o.SetDiamondCode(diamondCode)
	return o
}

// SetDiamondCode adds the diamondCode to the get comics collection params
func (o *GetComicsCollectionParams) SetDiamondCode(diamondCode *string) {
	o.DiamondCode = diamondCode
}

// WithDigitalID adds the digitalID to the get comics collection params
func (o *GetComicsCollectionParams) WithDigitalID(digitalID *int32) *GetComicsCollectionParams {
	o.SetDigitalID(digitalID)
	return o
}

// SetDigitalID adds the digitalId to the get comics collection params
func (o *GetComicsCollectionParams) SetDigitalID(digitalID *int32) {
	o.DigitalID = digitalID
}

// WithEan adds the ean to the get comics collection params
func (o *GetComicsCollectionParams) WithEan(ean *string) *GetComicsCollectionParams {
	o.SetEan(ean)
	return o
}

// SetEan adds the ean to the get comics collection params
func (o *GetComicsCollectionParams) SetEan(ean *string) {
	o.Ean = ean
}

// WithEvents adds the events to the get comics collection params
func (o *GetComicsCollectionParams) WithEvents(events []int32) *GetComicsCollectionParams {
	o.SetEvents(events)
	return o
}

// SetEvents adds the events to the get comics collection params
func (o *GetComicsCollectionParams) SetEvents(events []int32) {
	o.Events = events
}

// WithFormat adds the format to the get comics collection params
func (o *GetComicsCollectionParams) WithFormat(format *string) *GetComicsCollectionParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get comics collection params
func (o *GetComicsCollectionParams) SetFormat(format *string) {
	o.Format = format
}

// WithFormatType adds the formatType to the get comics collection params
func (o *GetComicsCollectionParams) WithFormatType(formatType *string) *GetComicsCollectionParams {
	o.SetFormatType(formatType)
	return o
}

// SetFormatType adds the formatType to the get comics collection params
func (o *GetComicsCollectionParams) SetFormatType(formatType *string) {
	o.FormatType = formatType
}

// WithHasDigitalIssue adds the hasDigitalIssue to the get comics collection params
func (o *GetComicsCollectionParams) WithHasDigitalIssue(hasDigitalIssue *bool) *GetComicsCollectionParams {
	o.SetHasDigitalIssue(hasDigitalIssue)
	return o
}

// SetHasDigitalIssue adds the hasDigitalIssue to the get comics collection params
func (o *GetComicsCollectionParams) SetHasDigitalIssue(hasDigitalIssue *bool) {
	o.HasDigitalIssue = hasDigitalIssue
}

// WithHash adds the hash to the get comics collection params
func (o *GetComicsCollectionParams) WithHash(hash string) *GetComicsCollectionParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get comics collection params
func (o *GetComicsCollectionParams) SetHash(hash string) {
	o.Hash = hash
}

// WithIsbn adds the isbn to the get comics collection params
func (o *GetComicsCollectionParams) WithIsbn(isbn *string) *GetComicsCollectionParams {
	o.SetIsbn(isbn)
	return o
}

// SetIsbn adds the isbn to the get comics collection params
func (o *GetComicsCollectionParams) SetIsbn(isbn *string) {
	o.Isbn = isbn
}

// WithIssn adds the issn to the get comics collection params
func (o *GetComicsCollectionParams) WithIssn(issn *string) *GetComicsCollectionParams {
	o.SetIssn(issn)
	return o
}

// SetIssn adds the issn to the get comics collection params
func (o *GetComicsCollectionParams) SetIssn(issn *string) {
	o.Issn = issn
}

// WithIssueNumber adds the issueNumber to the get comics collection params
func (o *GetComicsCollectionParams) WithIssueNumber(issueNumber *int32) *GetComicsCollectionParams {
	o.SetIssueNumber(issueNumber)
	return o
}

// SetIssueNumber adds the issueNumber to the get comics collection params
func (o *GetComicsCollectionParams) SetIssueNumber(issueNumber *int32) {
	o.IssueNumber = issueNumber
}

// WithLimit adds the limit to the get comics collection params
func (o *GetComicsCollectionParams) WithLimit(limit *int32) *GetComicsCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get comics collection params
func (o *GetComicsCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithModifiedSince adds the modifiedSince to the get comics collection params
func (o *GetComicsCollectionParams) WithModifiedSince(modifiedSince *strfmt.Date) *GetComicsCollectionParams {
	o.SetModifiedSince(modifiedSince)
	return o
}

// SetModifiedSince adds the modifiedSince to the get comics collection params
func (o *GetComicsCollectionParams) SetModifiedSince(modifiedSince *strfmt.Date) {
	o.ModifiedSince = modifiedSince
}

// WithNoVariants adds the noVariants to the get comics collection params
func (o *GetComicsCollectionParams) WithNoVariants(noVariants *bool) *GetComicsCollectionParams {
	o.SetNoVariants(noVariants)
	return o
}

// SetNoVariants adds the noVariants to the get comics collection params
func (o *GetComicsCollectionParams) SetNoVariants(noVariants *bool) {
	o.NoVariants = noVariants
}

// WithOffset adds the offset to the get comics collection params
func (o *GetComicsCollectionParams) WithOffset(offset *int32) *GetComicsCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get comics collection params
func (o *GetComicsCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get comics collection params
func (o *GetComicsCollectionParams) WithOrderBy(orderBy []string) *GetComicsCollectionParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get comics collection params
func (o *GetComicsCollectionParams) SetOrderBy(orderBy []string) {
	o.OrderBy = orderBy
}

// WithSeries adds the series to the get comics collection params
func (o *GetComicsCollectionParams) WithSeries(series []int32) *GetComicsCollectionParams {
	o.SetSeries(series)
	return o
}

// SetSeries adds the series to the get comics collection params
func (o *GetComicsCollectionParams) SetSeries(series []int32) {
	o.Series = series
}

// WithSharedAppearances adds the sharedAppearances to the get comics collection params
func (o *GetComicsCollectionParams) WithSharedAppearances(sharedAppearances []int32) *GetComicsCollectionParams {
	o.SetSharedAppearances(sharedAppearances)
	return o
}

// SetSharedAppearances adds the sharedAppearances to the get comics collection params
func (o *GetComicsCollectionParams) SetSharedAppearances(sharedAppearances []int32) {
	o.SharedAppearances = sharedAppearances
}

// WithStartYear adds the startYear to the get comics collection params
func (o *GetComicsCollectionParams) WithStartYear(startYear *int32) *GetComicsCollectionParams {
	o.SetStartYear(startYear)
	return o
}

// SetStartYear adds the startYear to the get comics collection params
func (o *GetComicsCollectionParams) SetStartYear(startYear *int32) {
	o.StartYear = startYear
}

// WithStories adds the stories to the get comics collection params
func (o *GetComicsCollectionParams) WithStories(stories []int32) *GetComicsCollectionParams {
	o.SetStories(stories)
	return o
}

// SetStories adds the stories to the get comics collection params
func (o *GetComicsCollectionParams) SetStories(stories []int32) {
	o.Stories = stories
}

// WithTitle adds the title to the get comics collection params
func (o *GetComicsCollectionParams) WithTitle(title *string) *GetComicsCollectionParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the get comics collection params
func (o *GetComicsCollectionParams) SetTitle(title *string) {
	o.Title = title
}

// WithTitleStartsWith adds the titleStartsWith to the get comics collection params
func (o *GetComicsCollectionParams) WithTitleStartsWith(titleStartsWith *string) *GetComicsCollectionParams {
	o.SetTitleStartsWith(titleStartsWith)
	return o
}

// SetTitleStartsWith adds the titleStartsWith to the get comics collection params
func (o *GetComicsCollectionParams) SetTitleStartsWith(titleStartsWith *string) {
	o.TitleStartsWith = titleStartsWith
}

// WithTs adds the ts to the get comics collection params
func (o *GetComicsCollectionParams) WithTs(ts string) *GetComicsCollectionParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get comics collection params
func (o *GetComicsCollectionParams) SetTs(ts string) {
	o.Ts = ts
}

// WithUpc adds the upc to the get comics collection params
func (o *GetComicsCollectionParams) WithUpc(upc *string) *GetComicsCollectionParams {
	o.SetUpc(upc)
	return o
}

// SetUpc adds the upc to the get comics collection params
func (o *GetComicsCollectionParams) SetUpc(upc *string) {
	o.Upc = upc
}

// WriteToRequest writes these params to a swagger request
func (o *GetComicsCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	var valuesCharacters []string
	for _, v := range o.Characters {
		valuesCharacters = append(valuesCharacters, swag.FormatInt32(v))
	}

	joinedCharacters := swag.JoinByFormat(valuesCharacters, "")
	// query array param characters
	if err := r.SetQueryParam("characters", joinedCharacters...); err != nil {
		return err
	}

	var valuesCollaborators []string
	for _, v := range o.Collaborators {
		valuesCollaborators = append(valuesCollaborators, swag.FormatInt32(v))
	}

	joinedCollaborators := swag.JoinByFormat(valuesCollaborators, "")
	// query array param collaborators
	if err := r.SetQueryParam("collaborators", joinedCollaborators...); err != nil {
		return err
	}

	var valuesCreators []string
	for _, v := range o.Creators {
		valuesCreators = append(valuesCreators, swag.FormatInt32(v))
	}

	joinedCreators := swag.JoinByFormat(valuesCreators, "")
	// query array param creators
	if err := r.SetQueryParam("creators", joinedCreators...); err != nil {
		return err
	}

	if o.DateDescriptor != nil {

		// query param dateDescriptor
		var qrDateDescriptor string
		if o.DateDescriptor != nil {
			qrDateDescriptor = *o.DateDescriptor
		}
		qDateDescriptor := qrDateDescriptor
		if qDateDescriptor != "" {
			if err := r.SetQueryParam("dateDescriptor", qDateDescriptor); err != nil {
				return err
			}
		}

	}

	var valuesDateRange []string
	for _, v := range o.DateRange {
		valuesDateRange = append(valuesDateRange, swag.FormatInt32(v))
	}

	joinedDateRange := swag.JoinByFormat(valuesDateRange, "")
	// query array param dateRange
	if err := r.SetQueryParam("dateRange", joinedDateRange...); err != nil {
		return err
	}

	if o.DiamondCode != nil {

		// query param diamondCode
		var qrDiamondCode string
		if o.DiamondCode != nil {
			qrDiamondCode = *o.DiamondCode
		}
		qDiamondCode := qrDiamondCode
		if qDiamondCode != "" {
			if err := r.SetQueryParam("diamondCode", qDiamondCode); err != nil {
				return err
			}
		}

	}

	if o.DigitalID != nil {

		// query param digitalId
		var qrDigitalID int32
		if o.DigitalID != nil {
			qrDigitalID = *o.DigitalID
		}
		qDigitalID := swag.FormatInt32(qrDigitalID)
		if qDigitalID != "" {
			if err := r.SetQueryParam("digitalId", qDigitalID); err != nil {
				return err
			}
		}

	}

	if o.Ean != nil {

		// query param ean
		var qrEan string
		if o.Ean != nil {
			qrEan = *o.Ean
		}
		qEan := qrEan
		if qEan != "" {
			if err := r.SetQueryParam("ean", qEan); err != nil {
				return err
			}
		}

	}

	var valuesEvents []string
	for _, v := range o.Events {
		valuesEvents = append(valuesEvents, swag.FormatInt32(v))
	}

	joinedEvents := swag.JoinByFormat(valuesEvents, "")
	// query array param events
	if err := r.SetQueryParam("events", joinedEvents...); err != nil {
		return err
	}

	if o.Format != nil {

		// query param format
		var qrFormat string
		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {
			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}

	}

	if o.FormatType != nil {

		// query param formatType
		var qrFormatType string
		if o.FormatType != nil {
			qrFormatType = *o.FormatType
		}
		qFormatType := qrFormatType
		if qFormatType != "" {
			if err := r.SetQueryParam("formatType", qFormatType); err != nil {
				return err
			}
		}

	}

	if o.HasDigitalIssue != nil {

		// query param hasDigitalIssue
		var qrHasDigitalIssue bool
		if o.HasDigitalIssue != nil {
			qrHasDigitalIssue = *o.HasDigitalIssue
		}
		qHasDigitalIssue := swag.FormatBool(qrHasDigitalIssue)
		if qHasDigitalIssue != "" {
			if err := r.SetQueryParam("hasDigitalIssue", qHasDigitalIssue); err != nil {
				return err
			}
		}

	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	if o.Isbn != nil {

		// query param isbn
		var qrIsbn string
		if o.Isbn != nil {
			qrIsbn = *o.Isbn
		}
		qIsbn := qrIsbn
		if qIsbn != "" {
			if err := r.SetQueryParam("isbn", qIsbn); err != nil {
				return err
			}
		}

	}

	if o.Issn != nil {

		// query param issn
		var qrIssn string
		if o.Issn != nil {
			qrIssn = *o.Issn
		}
		qIssn := qrIssn
		if qIssn != "" {
			if err := r.SetQueryParam("issn", qIssn); err != nil {
				return err
			}
		}

	}

	if o.IssueNumber != nil {

		// query param issueNumber
		var qrIssueNumber int32
		if o.IssueNumber != nil {
			qrIssueNumber = *o.IssueNumber
		}
		qIssueNumber := swag.FormatInt32(qrIssueNumber)
		if qIssueNumber != "" {
			if err := r.SetQueryParam("issueNumber", qIssueNumber); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.ModifiedSince != nil {

		// query param modifiedSince
		var qrModifiedSince strfmt.Date
		if o.ModifiedSince != nil {
			qrModifiedSince = *o.ModifiedSince
		}
		qModifiedSince := qrModifiedSince.String()
		if qModifiedSince != "" {
			if err := r.SetQueryParam("modifiedSince", qModifiedSince); err != nil {
				return err
			}
		}

	}

	if o.NoVariants != nil {

		// query param noVariants
		var qrNoVariants bool
		if o.NoVariants != nil {
			qrNoVariants = *o.NoVariants
		}
		qNoVariants := swag.FormatBool(qrNoVariants)
		if qNoVariants != "" {
			if err := r.SetQueryParam("noVariants", qNoVariants); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesOrderBy := o.OrderBy

	joinedOrderBy := swag.JoinByFormat(valuesOrderBy, "")
	// query array param orderBy
	if err := r.SetQueryParam("orderBy", joinedOrderBy...); err != nil {
		return err
	}

	var valuesSeries []string
	for _, v := range o.Series {
		valuesSeries = append(valuesSeries, swag.FormatInt32(v))
	}

	joinedSeries := swag.JoinByFormat(valuesSeries, "")
	// query array param series
	if err := r.SetQueryParam("series", joinedSeries...); err != nil {
		return err
	}

	var valuesSharedAppearances []string
	for _, v := range o.SharedAppearances {
		valuesSharedAppearances = append(valuesSharedAppearances, swag.FormatInt32(v))
	}

	joinedSharedAppearances := swag.JoinByFormat(valuesSharedAppearances, "")
	// query array param sharedAppearances
	if err := r.SetQueryParam("sharedAppearances", joinedSharedAppearances...); err != nil {
		return err
	}

	if o.StartYear != nil {

		// query param startYear
		var qrStartYear int32
		if o.StartYear != nil {
			qrStartYear = *o.StartYear
		}
		qStartYear := swag.FormatInt32(qrStartYear)
		if qStartYear != "" {
			if err := r.SetQueryParam("startYear", qStartYear); err != nil {
				return err
			}
		}

	}

	var valuesStories []string
	for _, v := range o.Stories {
		valuesStories = append(valuesStories, swag.FormatInt32(v))
	}

	joinedStories := swag.JoinByFormat(valuesStories, "")
	// query array param stories
	if err := r.SetQueryParam("stories", joinedStories...); err != nil {
		return err
	}

	if o.Title != nil {

		// query param title
		var qrTitle string
		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {
			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}

	}

	if o.TitleStartsWith != nil {

		// query param titleStartsWith
		var qrTitleStartsWith string
		if o.TitleStartsWith != nil {
			qrTitleStartsWith = *o.TitleStartsWith
		}
		qTitleStartsWith := qrTitleStartsWith
		if qTitleStartsWith != "" {
			if err := r.SetQueryParam("titleStartsWith", qTitleStartsWith); err != nil {
				return err
			}
		}

	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if o.Upc != nil {

		// query param upc
		var qrUpc string
		if o.Upc != nil {
			qrUpc = *o.Upc
		}
		qUpc := qrUpc
		if qUpc != "" {
			if err := r.SetQueryParam("upc", qUpc); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
