// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSeriesIndividualParams creates a new GetSeriesIndividualParams object
// with the default values initialized.
func NewGetSeriesIndividualParams() *GetSeriesIndividualParams {
	var ()
	return &GetSeriesIndividualParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSeriesIndividualParamsWithTimeout creates a new GetSeriesIndividualParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSeriesIndividualParamsWithTimeout(timeout time.Duration) *GetSeriesIndividualParams {
	var ()
	return &GetSeriesIndividualParams{

		timeout: timeout,
	}
}

// NewGetSeriesIndividualParamsWithContext creates a new GetSeriesIndividualParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSeriesIndividualParamsWithContext(ctx context.Context) *GetSeriesIndividualParams {
	var ()
	return &GetSeriesIndividualParams{

		Context: ctx,
	}
}

// NewGetSeriesIndividualParamsWithHTTPClient creates a new GetSeriesIndividualParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSeriesIndividualParamsWithHTTPClient(client *http.Client) *GetSeriesIndividualParams {
	var ()
	return &GetSeriesIndividualParams{
		HTTPClient: client,
	}
}

/*GetSeriesIndividualParams contains all the parameters to send to the API endpoint
for the get series individual operation typically these are written to a http.Request
*/
type GetSeriesIndividualParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*SeriesID
	  Filter by series title.

	*/
	SeriesID int32
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get series individual params
func (o *GetSeriesIndividualParams) WithTimeout(timeout time.Duration) *GetSeriesIndividualParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get series individual params
func (o *GetSeriesIndividualParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get series individual params
func (o *GetSeriesIndividualParams) WithContext(ctx context.Context) *GetSeriesIndividualParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get series individual params
func (o *GetSeriesIndividualParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get series individual params
func (o *GetSeriesIndividualParams) WithHTTPClient(client *http.Client) *GetSeriesIndividualParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get series individual params
func (o *GetSeriesIndividualParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get series individual params
func (o *GetSeriesIndividualParams) WithApikey(apikey string) *GetSeriesIndividualParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get series individual params
func (o *GetSeriesIndividualParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithHash adds the hash to the get series individual params
func (o *GetSeriesIndividualParams) WithHash(hash string) *GetSeriesIndividualParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get series individual params
func (o *GetSeriesIndividualParams) SetHash(hash string) {
	o.Hash = hash
}

// WithSeriesID adds the seriesID to the get series individual params
func (o *GetSeriesIndividualParams) WithSeriesID(seriesID int32) *GetSeriesIndividualParams {
	o.SetSeriesID(seriesID)
	return o
}

// SetSeriesID adds the seriesId to the get series individual params
func (o *GetSeriesIndividualParams) SetSeriesID(seriesID int32) {
	o.SeriesID = seriesID
}

// WithTs adds the ts to the get series individual params
func (o *GetSeriesIndividualParams) WithTs(ts string) *GetSeriesIndividualParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get series individual params
func (o *GetSeriesIndividualParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetSeriesIndividualParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	// path param seriesId
	if err := r.SetPathParam("seriesId", swag.FormatInt32(o.SeriesID)); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
