// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/mcapi-loader/marvel/models"
)

// GetSeriesCharacterWrapperReader is a Reader for the GetSeriesCharacterWrapper structure.
type GetSeriesCharacterWrapperReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSeriesCharacterWrapperReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSeriesCharacterWrapperOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSeriesCharacterWrapperOK creates a GetSeriesCharacterWrapperOK with default headers values
func NewGetSeriesCharacterWrapperOK() *GetSeriesCharacterWrapperOK {
	return &GetSeriesCharacterWrapperOK{}
}

/*GetSeriesCharacterWrapperOK handles this case with default header values.

No response was specified
*/
type GetSeriesCharacterWrapperOK struct {
	Payload *models.CharacterDataWrapper
}

func (o *GetSeriesCharacterWrapperOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/series/{seriesId}/characters][%d] getSeriesCharacterWrapperOK  %+v", 200, o.Payload)
}

func (o *GetSeriesCharacterWrapperOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CharacterDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
