// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/mcapi-loader/marvel/models"
)

// GetSeriesIndividualReader is a Reader for the GetSeriesIndividual structure.
type GetSeriesIndividualReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSeriesIndividualReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSeriesIndividualOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSeriesIndividualOK creates a GetSeriesIndividualOK with default headers values
func NewGetSeriesIndividualOK() *GetSeriesIndividualOK {
	return &GetSeriesIndividualOK{}
}

/*GetSeriesIndividualOK handles this case with default header values.

No response was specified
*/
type GetSeriesIndividualOK struct {
	Payload *models.SeriesDataWrapper
}

func (o *GetSeriesIndividualOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/series/{seriesId}][%d] getSeriesIndividualOK  %+v", 200, o.Payload)
}

func (o *GetSeriesIndividualOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SeriesDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
