// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/marvel-comics-api-data-loader/marvel/models"
)

// GetEventsCollectionReader is a Reader for the GetEventsCollection structure.
type GetEventsCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEventsCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEventsCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEventsCollectionOK creates a GetEventsCollectionOK with default headers values
func NewGetEventsCollectionOK() *GetEventsCollectionOK {
	return &GetEventsCollectionOK{}
}

/*GetEventsCollectionOK handles this case with default header values.

No response was specified
*/
type GetEventsCollectionOK struct {
	Payload *models.EventDataWrapper
}

func (o *GetEventsCollectionOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/events][%d] getEventsCollectionOK  %+v", 200, o.Payload)
}

func (o *GetEventsCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
