// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCharacterStoryCollectionParams creates a new GetCharacterStoryCollectionParams object
// with the default values initialized.
func NewGetCharacterStoryCollectionParams() *GetCharacterStoryCollectionParams {
	var ()
	return &GetCharacterStoryCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCharacterStoryCollectionParamsWithTimeout creates a new GetCharacterStoryCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCharacterStoryCollectionParamsWithTimeout(timeout time.Duration) *GetCharacterStoryCollectionParams {
	var ()
	return &GetCharacterStoryCollectionParams{

		timeout: timeout,
	}
}

// NewGetCharacterStoryCollectionParamsWithContext creates a new GetCharacterStoryCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCharacterStoryCollectionParamsWithContext(ctx context.Context) *GetCharacterStoryCollectionParams {
	var ()
	return &GetCharacterStoryCollectionParams{

		Context: ctx,
	}
}

// NewGetCharacterStoryCollectionParamsWithHTTPClient creates a new GetCharacterStoryCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCharacterStoryCollectionParamsWithHTTPClient(client *http.Client) *GetCharacterStoryCollectionParams {
	var ()
	return &GetCharacterStoryCollectionParams{
		HTTPClient: client,
	}
}

/*GetCharacterStoryCollectionParams contains all the parameters to send to the API endpoint
for the get character story collection operation typically these are written to a http.Request
*/
type GetCharacterStoryCollectionParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*CharacterID
	  The character ID.

	*/
	CharacterID int32
	/*Comics
	  Return only stories contained in the specified (accepts a comma-separated list of ids).

	*/
	Comics []int32
	/*Creators
	  Return only stories which feature work by the specified creators (accepts a comma-separated list of ids).

	*/
	Creators []int32
	/*Events
	  Return only stories which take place during the specified events (accepts a comma-separated list of ids).

	*/
	Events []int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Limit
	  Limit the result set to the specified number of resources.

	*/
	Limit *int32
	/*ModifiedSince
	  Return only stories which have been modified since the specified date.

	*/
	ModifiedSince *strfmt.Date
	/*Offset
	  Skip the specified number of resources in the result set.

	*/
	Offset *int32
	/*OrderBy
	  Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed.

	*/
	OrderBy []string
	/*Series
	  Return only stories contained the specified series (accepts a comma-separated list of ids).

	*/
	Series []int32
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithTimeout(timeout time.Duration) *GetCharacterStoryCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithContext(ctx context.Context) *GetCharacterStoryCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithHTTPClient(client *http.Client) *GetCharacterStoryCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithApikey(apikey string) *GetCharacterStoryCollectionParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithCharacterID adds the characterID to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithCharacterID(characterID int32) *GetCharacterStoryCollectionParams {
	o.SetCharacterID(characterID)
	return o
}

// SetCharacterID adds the characterId to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetCharacterID(characterID int32) {
	o.CharacterID = characterID
}

// WithComics adds the comics to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithComics(comics []int32) *GetCharacterStoryCollectionParams {
	o.SetComics(comics)
	return o
}

// SetComics adds the comics to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetComics(comics []int32) {
	o.Comics = comics
}

// WithCreators adds the creators to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithCreators(creators []int32) *GetCharacterStoryCollectionParams {
	o.SetCreators(creators)
	return o
}

// SetCreators adds the creators to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetCreators(creators []int32) {
	o.Creators = creators
}

// WithEvents adds the events to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithEvents(events []int32) *GetCharacterStoryCollectionParams {
	o.SetEvents(events)
	return o
}

// SetEvents adds the events to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetEvents(events []int32) {
	o.Events = events
}

// WithHash adds the hash to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithHash(hash string) *GetCharacterStoryCollectionParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetHash(hash string) {
	o.Hash = hash
}

// WithLimit adds the limit to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithLimit(limit *int32) *GetCharacterStoryCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithModifiedSince adds the modifiedSince to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithModifiedSince(modifiedSince *strfmt.Date) *GetCharacterStoryCollectionParams {
	o.SetModifiedSince(modifiedSince)
	return o
}

// SetModifiedSince adds the modifiedSince to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetModifiedSince(modifiedSince *strfmt.Date) {
	o.ModifiedSince = modifiedSince
}

// WithOffset adds the offset to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithOffset(offset *int32) *GetCharacterStoryCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithOrderBy(orderBy []string) *GetCharacterStoryCollectionParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetOrderBy(orderBy []string) {
	o.OrderBy = orderBy
}

// WithSeries adds the series to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithSeries(series []int32) *GetCharacterStoryCollectionParams {
	o.SetSeries(series)
	return o
}

// SetSeries adds the series to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetSeries(series []int32) {
	o.Series = series
}

// WithTs adds the ts to the get character story collection params
func (o *GetCharacterStoryCollectionParams) WithTs(ts string) *GetCharacterStoryCollectionParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get character story collection params
func (o *GetCharacterStoryCollectionParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetCharacterStoryCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	// path param characterId
	if err := r.SetPathParam("characterId", swag.FormatInt32(o.CharacterID)); err != nil {
		return err
	}

	var valuesComics []string
	for _, v := range o.Comics {
		valuesComics = append(valuesComics, swag.FormatInt32(v))
	}

	joinedComics := swag.JoinByFormat(valuesComics, "")
	// query array param comics
	if err := r.SetQueryParam("comics", joinedComics...); err != nil {
		return err
	}

	var valuesCreators []string
	for _, v := range o.Creators {
		valuesCreators = append(valuesCreators, swag.FormatInt32(v))
	}

	joinedCreators := swag.JoinByFormat(valuesCreators, "")
	// query array param creators
	if err := r.SetQueryParam("creators", joinedCreators...); err != nil {
		return err
	}

	var valuesEvents []string
	for _, v := range o.Events {
		valuesEvents = append(valuesEvents, swag.FormatInt32(v))
	}

	joinedEvents := swag.JoinByFormat(valuesEvents, "")
	// query array param events
	if err := r.SetQueryParam("events", joinedEvents...); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.ModifiedSince != nil {

		// query param modifiedSince
		var qrModifiedSince strfmt.Date
		if o.ModifiedSince != nil {
			qrModifiedSince = *o.ModifiedSince
		}
		qModifiedSince := qrModifiedSince.String()
		if qModifiedSince != "" {
			if err := r.SetQueryParam("modifiedSince", qModifiedSince); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesOrderBy := o.OrderBy

	joinedOrderBy := swag.JoinByFormat(valuesOrderBy, "")
	// query array param orderBy
	if err := r.SetQueryParam("orderBy", joinedOrderBy...); err != nil {
		return err
	}

	var valuesSeries []string
	for _, v := range o.Series {
		valuesSeries = append(valuesSeries, swag.FormatInt32(v))
	}

	joinedSeries := swag.JoinByFormat(valuesSeries, "")
	// query array param series
	if err := r.SetQueryParam("series", joinedSeries...); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
