// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventStoryCollectionParams creates a new GetEventStoryCollectionParams object
// with the default values initialized.
func NewGetEventStoryCollectionParams() *GetEventStoryCollectionParams {
	var ()
	return &GetEventStoryCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventStoryCollectionParamsWithTimeout creates a new GetEventStoryCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventStoryCollectionParamsWithTimeout(timeout time.Duration) *GetEventStoryCollectionParams {
	var ()
	return &GetEventStoryCollectionParams{

		timeout: timeout,
	}
}

// NewGetEventStoryCollectionParamsWithContext creates a new GetEventStoryCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEventStoryCollectionParamsWithContext(ctx context.Context) *GetEventStoryCollectionParams {
	var ()
	return &GetEventStoryCollectionParams{

		Context: ctx,
	}
}

// NewGetEventStoryCollectionParamsWithHTTPClient creates a new GetEventStoryCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEventStoryCollectionParamsWithHTTPClient(client *http.Client) *GetEventStoryCollectionParams {
	var ()
	return &GetEventStoryCollectionParams{
		HTTPClient: client,
	}
}

/*GetEventStoryCollectionParams contains all the parameters to send to the API endpoint
for the get event story collection operation typically these are written to a http.Request
*/
type GetEventStoryCollectionParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*Characters
	  Return only stories which feature the specified characters (accepts a comma-separated list of ids).

	*/
	Characters []int32
	/*Comics
	  Return only stories contained in the specified (accepts a comma-separated list of ids).

	*/
	Comics []int32
	/*Creators
	  Return only stories which feature work by the specified creators (accepts a comma-separated list of ids).

	*/
	Creators []int32
	/*EventID
	  The ID of the event.

	*/
	EventID int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Limit
	  Limit the result set to the specified number of resources.

	*/
	Limit *int32
	/*ModifiedSince
	  Return only stories which have been modified since the specified date.

	*/
	ModifiedSince *strfmt.Date
	/*Offset
	  Skip the specified number of resources in the result set.

	*/
	Offset *int32
	/*OrderBy
	  Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed.

	*/
	OrderBy []string
	/*Series
	  Return only stories contained the specified series (accepts a comma-separated list of ids).

	*/
	Series []int32
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get event story collection params
func (o *GetEventStoryCollectionParams) WithTimeout(timeout time.Duration) *GetEventStoryCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event story collection params
func (o *GetEventStoryCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event story collection params
func (o *GetEventStoryCollectionParams) WithContext(ctx context.Context) *GetEventStoryCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event story collection params
func (o *GetEventStoryCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event story collection params
func (o *GetEventStoryCollectionParams) WithHTTPClient(client *http.Client) *GetEventStoryCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event story collection params
func (o *GetEventStoryCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get event story collection params
func (o *GetEventStoryCollectionParams) WithApikey(apikey string) *GetEventStoryCollectionParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get event story collection params
func (o *GetEventStoryCollectionParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithCharacters adds the characters to the get event story collection params
func (o *GetEventStoryCollectionParams) WithCharacters(characters []int32) *GetEventStoryCollectionParams {
	o.SetCharacters(characters)
	return o
}

// SetCharacters adds the characters to the get event story collection params
func (o *GetEventStoryCollectionParams) SetCharacters(characters []int32) {
	o.Characters = characters
}

// WithComics adds the comics to the get event story collection params
func (o *GetEventStoryCollectionParams) WithComics(comics []int32) *GetEventStoryCollectionParams {
	o.SetComics(comics)
	return o
}

// SetComics adds the comics to the get event story collection params
func (o *GetEventStoryCollectionParams) SetComics(comics []int32) {
	o.Comics = comics
}

// WithCreators adds the creators to the get event story collection params
func (o *GetEventStoryCollectionParams) WithCreators(creators []int32) *GetEventStoryCollectionParams {
	o.SetCreators(creators)
	return o
}

// SetCreators adds the creators to the get event story collection params
func (o *GetEventStoryCollectionParams) SetCreators(creators []int32) {
	o.Creators = creators
}

// WithEventID adds the eventID to the get event story collection params
func (o *GetEventStoryCollectionParams) WithEventID(eventID int32) *GetEventStoryCollectionParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get event story collection params
func (o *GetEventStoryCollectionParams) SetEventID(eventID int32) {
	o.EventID = eventID
}

// WithHash adds the hash to the get event story collection params
func (o *GetEventStoryCollectionParams) WithHash(hash string) *GetEventStoryCollectionParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get event story collection params
func (o *GetEventStoryCollectionParams) SetHash(hash string) {
	o.Hash = hash
}

// WithLimit adds the limit to the get event story collection params
func (o *GetEventStoryCollectionParams) WithLimit(limit *int32) *GetEventStoryCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get event story collection params
func (o *GetEventStoryCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithModifiedSince adds the modifiedSince to the get event story collection params
func (o *GetEventStoryCollectionParams) WithModifiedSince(modifiedSince *strfmt.Date) *GetEventStoryCollectionParams {
	o.SetModifiedSince(modifiedSince)
	return o
}

// SetModifiedSince adds the modifiedSince to the get event story collection params
func (o *GetEventStoryCollectionParams) SetModifiedSince(modifiedSince *strfmt.Date) {
	o.ModifiedSince = modifiedSince
}

// WithOffset adds the offset to the get event story collection params
func (o *GetEventStoryCollectionParams) WithOffset(offset *int32) *GetEventStoryCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get event story collection params
func (o *GetEventStoryCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get event story collection params
func (o *GetEventStoryCollectionParams) WithOrderBy(orderBy []string) *GetEventStoryCollectionParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get event story collection params
func (o *GetEventStoryCollectionParams) SetOrderBy(orderBy []string) {
	o.OrderBy = orderBy
}

// WithSeries adds the series to the get event story collection params
func (o *GetEventStoryCollectionParams) WithSeries(series []int32) *GetEventStoryCollectionParams {
	o.SetSeries(series)
	return o
}

// SetSeries adds the series to the get event story collection params
func (o *GetEventStoryCollectionParams) SetSeries(series []int32) {
	o.Series = series
}

// WithTs adds the ts to the get event story collection params
func (o *GetEventStoryCollectionParams) WithTs(ts string) *GetEventStoryCollectionParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get event story collection params
func (o *GetEventStoryCollectionParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventStoryCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	var valuesCharacters []string
	for _, v := range o.Characters {
		valuesCharacters = append(valuesCharacters, swag.FormatInt32(v))
	}

	joinedCharacters := swag.JoinByFormat(valuesCharacters, "")
	// query array param characters
	if err := r.SetQueryParam("characters", joinedCharacters...); err != nil {
		return err
	}

	var valuesComics []string
	for _, v := range o.Comics {
		valuesComics = append(valuesComics, swag.FormatInt32(v))
	}

	joinedComics := swag.JoinByFormat(valuesComics, "")
	// query array param comics
	if err := r.SetQueryParam("comics", joinedComics...); err != nil {
		return err
	}

	var valuesCreators []string
	for _, v := range o.Creators {
		valuesCreators = append(valuesCreators, swag.FormatInt32(v))
	}

	joinedCreators := swag.JoinByFormat(valuesCreators, "")
	// query array param creators
	if err := r.SetQueryParam("creators", joinedCreators...); err != nil {
		return err
	}

	// path param eventId
	if err := r.SetPathParam("eventId", swag.FormatInt32(o.EventID)); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.ModifiedSince != nil {

		// query param modifiedSince
		var qrModifiedSince strfmt.Date
		if o.ModifiedSince != nil {
			qrModifiedSince = *o.ModifiedSince
		}
		qModifiedSince := qrModifiedSince.String()
		if qModifiedSince != "" {
			if err := r.SetQueryParam("modifiedSince", qModifiedSince); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesOrderBy := o.OrderBy

	joinedOrderBy := swag.JoinByFormat(valuesOrderBy, "")
	// query array param orderBy
	if err := r.SetQueryParam("orderBy", joinedOrderBy...); err != nil {
		return err
	}

	var valuesSeries []string
	for _, v := range o.Series {
		valuesSeries = append(valuesSeries, swag.FormatInt32(v))
	}

	joinedSeries := swag.JoinByFormat(valuesSeries, "")
	// query array param series
	if err := r.SetQueryParam("series", joinedSeries...); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
