// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/mcapi-loader/marvel/models"
)

// GetComicsCollectionByStoryIDReader is a Reader for the GetComicsCollectionByStoryID structure.
type GetComicsCollectionByStoryIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComicsCollectionByStoryIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetComicsCollectionByStoryIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetComicsCollectionByStoryIDOK creates a GetComicsCollectionByStoryIDOK with default headers values
func NewGetComicsCollectionByStoryIDOK() *GetComicsCollectionByStoryIDOK {
	return &GetComicsCollectionByStoryIDOK{}
}

/*GetComicsCollectionByStoryIDOK handles this case with default header values.

No response was specified
*/
type GetComicsCollectionByStoryIDOK struct {
	Payload *models.ComicDataWrapper
}

func (o *GetComicsCollectionByStoryIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/stories/{storyId}/comics][%d] getComicsCollectionByStoryIdOK  %+v", 200, o.Payload)
}

func (o *GetComicsCollectionByStoryIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComicDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
