// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/marvel-comics-api-data-loader/marvel/models"
)

// GetCharacterIndividualReader is a Reader for the GetCharacterIndividual structure.
type GetCharacterIndividualReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharacterIndividualReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCharacterIndividualOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCharacterIndividualOK creates a GetCharacterIndividualOK with default headers values
func NewGetCharacterIndividualOK() *GetCharacterIndividualOK {
	return &GetCharacterIndividualOK{}
}

/*GetCharacterIndividualOK handles this case with default header values.

No response was specified
*/
type GetCharacterIndividualOK struct {
	Payload *models.CharacterDataWrapper
}

func (o *GetCharacterIndividualOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/characters/{characterId}][%d] getCharacterIndividualOK  %+v", 200, o.Payload)
}

func (o *GetCharacterIndividualOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CharacterDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
