// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/mcapi-loader/marvel/models"
)

// GetIssueEventsCollectionReader is a Reader for the GetIssueEventsCollection structure.
type GetIssueEventsCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIssueEventsCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIssueEventsCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIssueEventsCollectionOK creates a GetIssueEventsCollectionOK with default headers values
func NewGetIssueEventsCollectionOK() *GetIssueEventsCollectionOK {
	return &GetIssueEventsCollectionOK{}
}

/*GetIssueEventsCollectionOK handles this case with default header values.

No response was specified
*/
type GetIssueEventsCollectionOK struct {
	Payload *models.EventDataWrapper
}

func (o *GetIssueEventsCollectionOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/comics/{comicId}/events][%d] getIssueEventsCollectionOK  %+v", 200, o.Payload)
}

func (o *GetIssueEventsCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EventDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
