// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetComicIndividualParams creates a new GetComicIndividualParams object
// with the default values initialized.
func NewGetComicIndividualParams() *GetComicIndividualParams {
	var ()
	return &GetComicIndividualParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetComicIndividualParamsWithTimeout creates a new GetComicIndividualParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetComicIndividualParamsWithTimeout(timeout time.Duration) *GetComicIndividualParams {
	var ()
	return &GetComicIndividualParams{

		timeout: timeout,
	}
}

// NewGetComicIndividualParamsWithContext creates a new GetComicIndividualParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetComicIndividualParamsWithContext(ctx context.Context) *GetComicIndividualParams {
	var ()
	return &GetComicIndividualParams{

		Context: ctx,
	}
}

// NewGetComicIndividualParamsWithHTTPClient creates a new GetComicIndividualParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetComicIndividualParamsWithHTTPClient(client *http.Client) *GetComicIndividualParams {
	var ()
	return &GetComicIndividualParams{
		HTTPClient: client,
	}
}

/*GetComicIndividualParams contains all the parameters to send to the API endpoint
for the get comic individual operation typically these are written to a http.Request
*/
type GetComicIndividualParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*ComicID
	  A single comic.

	*/
	ComicID int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get comic individual params
func (o *GetComicIndividualParams) WithTimeout(timeout time.Duration) *GetComicIndividualParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get comic individual params
func (o *GetComicIndividualParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get comic individual params
func (o *GetComicIndividualParams) WithContext(ctx context.Context) *GetComicIndividualParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get comic individual params
func (o *GetComicIndividualParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get comic individual params
func (o *GetComicIndividualParams) WithHTTPClient(client *http.Client) *GetComicIndividualParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get comic individual params
func (o *GetComicIndividualParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get comic individual params
func (o *GetComicIndividualParams) WithApikey(apikey string) *GetComicIndividualParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get comic individual params
func (o *GetComicIndividualParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithComicID adds the comicID to the get comic individual params
func (o *GetComicIndividualParams) WithComicID(comicID int32) *GetComicIndividualParams {
	o.SetComicID(comicID)
	return o
}

// SetComicID adds the comicId to the get comic individual params
func (o *GetComicIndividualParams) SetComicID(comicID int32) {
	o.ComicID = comicID
}

// WithHash adds the hash to the get comic individual params
func (o *GetComicIndividualParams) WithHash(hash string) *GetComicIndividualParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get comic individual params
func (o *GetComicIndividualParams) SetHash(hash string) {
	o.Hash = hash
}

// WithTs adds the ts to the get comic individual params
func (o *GetComicIndividualParams) WithTs(ts string) *GetComicIndividualParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get comic individual params
func (o *GetComicIndividualParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetComicIndividualParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	// path param comicId
	if err := r.SetPathParam("comicId", swag.FormatInt32(o.ComicID)); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
