// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIssueEventsCollectionParams creates a new GetIssueEventsCollectionParams object
// with the default values initialized.
func NewGetIssueEventsCollectionParams() *GetIssueEventsCollectionParams {
	var ()
	return &GetIssueEventsCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIssueEventsCollectionParamsWithTimeout creates a new GetIssueEventsCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIssueEventsCollectionParamsWithTimeout(timeout time.Duration) *GetIssueEventsCollectionParams {
	var ()
	return &GetIssueEventsCollectionParams{

		timeout: timeout,
	}
}

// NewGetIssueEventsCollectionParamsWithContext creates a new GetIssueEventsCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIssueEventsCollectionParamsWithContext(ctx context.Context) *GetIssueEventsCollectionParams {
	var ()
	return &GetIssueEventsCollectionParams{

		Context: ctx,
	}
}

// NewGetIssueEventsCollectionParamsWithHTTPClient creates a new GetIssueEventsCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIssueEventsCollectionParamsWithHTTPClient(client *http.Client) *GetIssueEventsCollectionParams {
	var ()
	return &GetIssueEventsCollectionParams{
		HTTPClient: client,
	}
}

/*GetIssueEventsCollectionParams contains all the parameters to send to the API endpoint
for the get issue events collection operation typically these are written to a http.Request
*/
type GetIssueEventsCollectionParams struct {

	/*Apikey
	  [Auth] public apikey

	*/
	Apikey string
	/*Characters
	  Return only events which feature the specified characters (accepts a comma-separated list of ids).

	*/
	Characters []int32
	/*ComicID
	  The comic ID.

	*/
	ComicID int32
	/*Creators
	  Return only events which feature work by the specified creators (accepts a comma-separated list of ids).

	*/
	Creators []int32
	/*Hash
	  [Auth] md5 digest of concatenation of ts, private key, public key

	*/
	Hash string
	/*Limit
	  Limit the result set to the specified number of resources.

	*/
	Limit *int32
	/*ModifiedSince
	  Return only events which have been modified since the specified date.

	*/
	ModifiedSince *strfmt.Date
	/*Name
	  Filter the event list by name.

	*/
	Name *string
	/*NameStartsWith
	  Return events with names that begin with the specified string (e.g. Sp).

	*/
	NameStartsWith *string
	/*Offset
	  Skip the specified number of resources in the result set.

	*/
	Offset *int32
	/*OrderBy
	  Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed.

	*/
	OrderBy []string
	/*Series
	  Return only events which are part of the specified series (accepts a comma-separated list of ids).

	*/
	Series []int32
	/*Stories
	  Return only events which contain the specified stories (accepts a comma-separated list of ids).

	*/
	Stories []int32
	/*Ts
	  [Auth] timestamp

	*/
	Ts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithTimeout(timeout time.Duration) *GetIssueEventsCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithContext(ctx context.Context) *GetIssueEventsCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithHTTPClient(client *http.Client) *GetIssueEventsCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApikey adds the apikey to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithApikey(apikey string) *GetIssueEventsCollectionParams {
	o.SetApikey(apikey)
	return o
}

// SetApikey adds the apikey to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetApikey(apikey string) {
	o.Apikey = apikey
}

// WithCharacters adds the characters to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithCharacters(characters []int32) *GetIssueEventsCollectionParams {
	o.SetCharacters(characters)
	return o
}

// SetCharacters adds the characters to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetCharacters(characters []int32) {
	o.Characters = characters
}

// WithComicID adds the comicID to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithComicID(comicID int32) *GetIssueEventsCollectionParams {
	o.SetComicID(comicID)
	return o
}

// SetComicID adds the comicId to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetComicID(comicID int32) {
	o.ComicID = comicID
}

// WithCreators adds the creators to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithCreators(creators []int32) *GetIssueEventsCollectionParams {
	o.SetCreators(creators)
	return o
}

// SetCreators adds the creators to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetCreators(creators []int32) {
	o.Creators = creators
}

// WithHash adds the hash to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithHash(hash string) *GetIssueEventsCollectionParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetHash(hash string) {
	o.Hash = hash
}

// WithLimit adds the limit to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithLimit(limit *int32) *GetIssueEventsCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithModifiedSince adds the modifiedSince to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithModifiedSince(modifiedSince *strfmt.Date) *GetIssueEventsCollectionParams {
	o.SetModifiedSince(modifiedSince)
	return o
}

// SetModifiedSince adds the modifiedSince to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetModifiedSince(modifiedSince *strfmt.Date) {
	o.ModifiedSince = modifiedSince
}

// WithName adds the name to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithName(name *string) *GetIssueEventsCollectionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetName(name *string) {
	o.Name = name
}

// WithNameStartsWith adds the nameStartsWith to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithNameStartsWith(nameStartsWith *string) *GetIssueEventsCollectionParams {
	o.SetNameStartsWith(nameStartsWith)
	return o
}

// SetNameStartsWith adds the nameStartsWith to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetNameStartsWith(nameStartsWith *string) {
	o.NameStartsWith = nameStartsWith
}

// WithOffset adds the offset to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithOffset(offset *int32) *GetIssueEventsCollectionParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithOrderBy(orderBy []string) *GetIssueEventsCollectionParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetOrderBy(orderBy []string) {
	o.OrderBy = orderBy
}

// WithSeries adds the series to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithSeries(series []int32) *GetIssueEventsCollectionParams {
	o.SetSeries(series)
	return o
}

// SetSeries adds the series to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetSeries(series []int32) {
	o.Series = series
}

// WithStories adds the stories to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithStories(stories []int32) *GetIssueEventsCollectionParams {
	o.SetStories(stories)
	return o
}

// SetStories adds the stories to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetStories(stories []int32) {
	o.Stories = stories
}

// WithTs adds the ts to the get issue events collection params
func (o *GetIssueEventsCollectionParams) WithTs(ts string) *GetIssueEventsCollectionParams {
	o.SetTs(ts)
	return o
}

// SetTs adds the ts to the get issue events collection params
func (o *GetIssueEventsCollectionParams) SetTs(ts string) {
	o.Ts = ts
}

// WriteToRequest writes these params to a swagger request
func (o *GetIssueEventsCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apikey
	qrApikey := o.Apikey
	qApikey := qrApikey
	if qApikey != "" {
		if err := r.SetQueryParam("apikey", qApikey); err != nil {
			return err
		}
	}

	var valuesCharacters []string
	for _, v := range o.Characters {
		valuesCharacters = append(valuesCharacters, swag.FormatInt32(v))
	}

	joinedCharacters := swag.JoinByFormat(valuesCharacters, "")
	// query array param characters
	if err := r.SetQueryParam("characters", joinedCharacters...); err != nil {
		return err
	}

	// path param comicId
	if err := r.SetPathParam("comicId", swag.FormatInt32(o.ComicID)); err != nil {
		return err
	}

	var valuesCreators []string
	for _, v := range o.Creators {
		valuesCreators = append(valuesCreators, swag.FormatInt32(v))
	}

	joinedCreators := swag.JoinByFormat(valuesCreators, "")
	// query array param creators
	if err := r.SetQueryParam("creators", joinedCreators...); err != nil {
		return err
	}

	// query param hash
	qrHash := o.Hash
	qHash := qrHash
	if qHash != "" {
		if err := r.SetQueryParam("hash", qHash); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.ModifiedSince != nil {

		// query param modifiedSince
		var qrModifiedSince strfmt.Date
		if o.ModifiedSince != nil {
			qrModifiedSince = *o.ModifiedSince
		}
		qModifiedSince := qrModifiedSince.String()
		if qModifiedSince != "" {
			if err := r.SetQueryParam("modifiedSince", qModifiedSince); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.NameStartsWith != nil {

		// query param nameStartsWith
		var qrNameStartsWith string
		if o.NameStartsWith != nil {
			qrNameStartsWith = *o.NameStartsWith
		}
		qNameStartsWith := qrNameStartsWith
		if qNameStartsWith != "" {
			if err := r.SetQueryParam("nameStartsWith", qNameStartsWith); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	valuesOrderBy := o.OrderBy

	joinedOrderBy := swag.JoinByFormat(valuesOrderBy, "")
	// query array param orderBy
	if err := r.SetQueryParam("orderBy", joinedOrderBy...); err != nil {
		return err
	}

	var valuesSeries []string
	for _, v := range o.Series {
		valuesSeries = append(valuesSeries, swag.FormatInt32(v))
	}

	joinedSeries := swag.JoinByFormat(valuesSeries, "")
	// query array param series
	if err := r.SetQueryParam("series", joinedSeries...); err != nil {
		return err
	}

	var valuesStories []string
	for _, v := range o.Stories {
		valuesStories = append(valuesStories, swag.FormatInt32(v))
	}

	joinedStories := swag.JoinByFormat(valuesStories, "")
	// query array param stories
	if err := r.SetQueryParam("stories", joinedStories...); err != nil {
		return err
	}

	// query param ts
	qrTs := o.Ts
	qTs := qrTs
	if qTs != "" {
		if err := r.SetQueryParam("ts", qTs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
