// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/loivis/mcapi-loader/marvel/models"
)

// GetCreatorStoryCollectionReader is a Reader for the GetCreatorStoryCollection structure.
type GetCreatorStoryCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCreatorStoryCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCreatorStoryCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCreatorStoryCollectionOK creates a GetCreatorStoryCollectionOK with default headers values
func NewGetCreatorStoryCollectionOK() *GetCreatorStoryCollectionOK {
	return &GetCreatorStoryCollectionOK{}
}

/*GetCreatorStoryCollectionOK handles this case with default header values.

No response was specified
*/
type GetCreatorStoryCollectionOK struct {
	Payload *models.StoryDataWrapper
}

func (o *GetCreatorStoryCollectionOK) Error() string {
	return fmt.Sprintf("[GET /v1/public/creators/{creatorId}/stories][%d] getCreatorStoryCollectionOK  %+v", 200, o.Payload)
}

func (o *GetCreatorStoryCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StoryDataWrapper)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
