// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ComicSummary comic summary
// swagger:model ComicSummary
type ComicSummary struct {

	// The canonical name of the comic.
	Name string `json:"name,omitempty"`

	// The path to the individual comic resource.
	ResourceURI string `json:"resourceURI,omitempty"`
}

// Validate validates this comic summary
func (m *ComicSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComicSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComicSummary) UnmarshalBinary(b []byte) error {
	var res ComicSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
