// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ComicPrice comic price
// swagger:model ComicPrice
type ComicPrice struct {

	// The price (all prices in USD).
	Price float32 `json:"price,omitempty"`

	// A description of the price (e.g. print price, digital price).
	Type string `json:"type,omitempty"`
}

// Validate validates this comic price
func (m *ComicPrice) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComicPrice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComicPrice) UnmarshalBinary(b []byte) error {
	var res ComicPrice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
